language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t nabaraj/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nabaraj/docker-react npm run test
